VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "demo"
    #config.vm.network "private_network", ip: "192.168.33.16"
	config.vm.provision "docker"
	#config.ssh.port = 22
    #config.ssh.username = 'root'
    #config.ssh.private_key_path = 'phusion.key'
	config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
	
	config.vm.network :forwarded_port, guest: 5432, host: 5432
    config.vm.network :forwarded_port, guest: 80, host: 8080
	
	config.vm.provision "shell", inline: "echo hello"
	
	config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
end
