VAGRANTFILE_API_VERSION = "2"  
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "postgres" do |v|
    v.vm.provider "docker" do |d|
      d.image = "paintedfox/postgresql"
      d.volumes = ["/var/docker/postgresql:/data"]
	  d.ports = ["5432:5432"]
      d.env = {
        USER: "root",
        PASS: "abcdEF123456",
        DB: "root"
      }
      d.vagrant_vagrantfile = "../Dev/Vagrantfile"
    end
  end
  
  config.vm.define "app" do |v|
    v.vm.provider "docker" do |d|
      d.image = "phusion/baseimage"
	  d.has_ssh = true
	  d.ports = ["80:8080"]
	  d.cmd     = ["/sbin/my_init", "--enable-insecure-key"]
      d.vagrant_vagrantfile = "../Dev/Vagrantfile"
    end
  end

end  